# $schema: 'https://yazi-rs.github.io/schemas/yazi.json'

[mgr]
title_format = "{cwd}> yazi"

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
