# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  theme:
    selectedLineBgColor:
      - '#1a4759'
  lightTheme:
    selectedLineBgColor:
      - '#dcd5ac'
